"""Resolve an mddb calendar deck into the event occurrences within a time window.

Recurring masters carry ``rrule``+``exdate``+``rdate`` and are expanded at read time
(plain instances are never materialised); RECURRENCE-ID exceptions are their own
cards keyed ``uid``+``recurrence_id``. `events_in_window` returns the occurrences
overlapping a half-open window — expanding masters, subtracting EXDATEs, and
suppressing slots overridden by exception cards (which surface concretely at their
own time). Each occurrence carries a computed ``hidden`` flag from a master's
non-owned hide annotations (``mdcal/hidden`` tag / ``hidden_occurrences`` /
``hidden_from``), applied to its exception cards too — hide is a rendering hint,
not a filter, so hidden occurrences are still returned. Library code composing over
the public `mddb.MDDB` surface; the substrate stays calendar-agnostic.
"""

import datetime as _dt
from dataclasses import dataclass
from zoneinfo import ZoneInfo

import yaml as _yaml
from dateutil.rrule import rrulestr
from mddb import Card

from mdcal.ics import RECURRENCE_FOREVER_EPOCH, normalise_until

_LOADER = getattr(_yaml, "CSafeLoader", _yaml.SafeLoader)
"""SafeLoader semantics on the resolver's hottest path.

``CSafeLoader`` is the libyaml C implementation of ``SafeLoader`` — identical
parse semantics, ~9x faster (measured 199ms → 23ms for a month window's 450
cards on the Research deck). Falls back to the pure-Python ``SafeLoader`` on
PyYAML builds without libyaml.
"""


def _card(yaml_text, body):
    return Card(yaml=_yaml.load(yaml_text, Loader=_LOADER), body=body)


@dataclass
class Occurrence:
    """One concrete event occurrence to render.

    Attributes:
        card: The mddb ``Card`` — the recurring master for a generated instance,
            or the concrete (single / exception) card itself.
        start: This occurrence's start — a ``datetime.date`` for an all-day event,
            a tz-aware ``datetime.datetime`` otherwise.
        end: This occurrence's end, with the same typing as ``start``.
        recurring: ``True`` if generated by expanding a master's ``rrule``;
            ``False`` for a stored concrete card.
        hidden: ``True`` if a hide annotation covers this occurrence — the whole
            series (`mdcal/hidden` tag), this instant (`hidden_occurrences`), or
            a ray from an instant onward (`hidden_from`). The resolver applies a
            master's annotations to BOTH its generated occurrences and its
            promoted exception cards (same uid), which the grid alone could not.
            A rendering hint, not a filter: the resolver still returns hidden
            occurrences so a "show hidden" view can reveal them.
    """

    card: Card
    start: _dt.date | _dt.datetime
    end: _dt.date | _dt.datetime
    recurring: bool
    hidden: bool = False


def _instant(value):
    """Return the UTC-second epoch for a ``date`` or tz-aware ``datetime``.

    Mirrors the importer's epoch convention so ``date`` and ``datetime`` values
    compare uniformly: a ``date`` maps to its UTC-midnight epoch; a ``datetime``
    must be tz-aware.

    Args:
        value: A ``datetime.date`` or tz-aware ``datetime.datetime``.

    Returns:
        Integer UTC-second epoch.

    Raises:
        ValueError: ``value`` is a naive ``datetime`` (no silent localisation).
    """
    if isinstance(value, _dt.datetime):
        if value.tzinfo is None:
            raise ValueError(f"naive datetime not supported: {value!r}")
        return int(value.timestamp())
    midnight = _dt.datetime(value.year, value.month, value.day, tzinfo=_dt.timezone.utc)
    return int(midnight.timestamp())


def _concrete(db, start_epoch, end_epoch, hide):
    rows = db.conn.execute(
        "SELECT e.yaml_text, e.body FROM entries e "
        "JOIN entry_fields ds ON ds.entry_rowid=e.rowid AND ds.key='dtstart_epoch' "
        "JOIN entry_fields de ON de.entry_rowid=e.rowid AND de.key='dtend_epoch' "
        "LEFT JOIN entry_fields rr ON rr.entry_rowid=e.rowid AND rr.key='rrule' "
        "WHERE ds.value_num < ? AND de.value_num > ? AND rr.entry_rowid IS NULL",
        (end_epoch, start_epoch),
    ).fetchall()
    out = []
    for yaml_text, body in rows:
        card = _card(yaml_text, body)
        if card.yaml["status"] == "CANCELLED":
            continue
        hidden = hide(card, _instant(card.yaml["dtstart"]))
        out.append(
            Occurrence(card, card.yaml["dtstart"], card.yaml["dtend"], False, hidden)
        )
    return out


def _hide_policy(db):
    """Per-``(source, uid)`` hide annotations from every recurring master.

    Same single-pass-scan idiom as `_suppression_map`. A master's
    ``mdcal/hidden`` tag (whole series), ``hidden_occurrences`` (epoch points),
    and ``hidden_from`` (epoch ray) are non-owned annotations that must apply
    to the master's exception cards too — those are separate cards, so only a
    keyed policy built here reaches them. Keyed by ``(source, uid)`` because
    that is mdcal's sync identity: the same iCal UID in two sources is two
    events, and hiding one master must not touch the other. Returns a
    ``hide(card, instant) -> bool`` closure combining the master policy with
    the occurrence card's OWN ``mdcal/hidden`` tag (which covers single events
    and directly hidden exception cards).
    """
    uids = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_str FROM entry_fields WHERE key='uid'"
        ).fetchall()
    )
    sources = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_str FROM entry_fields WHERE key='source'"
        ).fetchall()
    )
    masters = {
        rowid
        for (rowid,) in db.conn.execute(
            "SELECT entry_rowid FROM entry_fields WHERE key='rrule'"
        )
    }

    def key(rowid):
        return (sources[rowid], uids[rowid])

    series = {
        key(rowid)
        for (rowid,) in db.conn.execute(
            "SELECT entry_rowid FROM entry_fields "
            "WHERE key='tags' AND value_str='mdcal/hidden'"
        )
        if rowid in masters
    }
    froms = {
        key(rowid): int(value)
        for rowid, value in db.conn.execute(
            "SELECT entry_rowid, value_num FROM entry_fields WHERE key='hidden_from'"
        )
        if rowid in masters
    }
    points = {}
    for rowid, value in db.conn.execute(
        "SELECT entry_rowid, value_num FROM entry_fields WHERE key='hidden_occurrences'"
    ):
        if rowid in masters:
            points.setdefault(key(rowid), set()).add(int(value))

    def hide(card, instant):
        k = (card.yaml["source"], card.yaml["uid"])
        return (
            "mdcal/hidden" in (card.yaml.get("tags") or [])
            or k in series
            or instant in points.get(k, ())
            or (k in froms and instant >= froms[k])
        )

    return hide


def _suppression_map(db):
    """Map each ``(source, uid)`` to the recurrence-id epochs it overrides.

    Keyed by ``(source, uid)``, not ``uid``: the same iCal UID in two sources
    is two distinct events (mdcal's sync identity is ``source + uid +
    recurrence_id``), so an exception in one must not suppress the other's
    generated slot. Single-pass index scans joined in Python: SQLite has no
    ``(entry_rowid, key)`` index on ``entry_fields``, so joining the key ranges
    in SQL nested-loops every row (measured 436ms on the 3,867-card deck vs
    ~5ms this way).
    """
    uids = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_str FROM entry_fields WHERE key='uid'"
        ).fetchall()
    )
    sources = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_str FROM entry_fields WHERE key='source'"
        ).fetchall()
    )
    out = {}
    for entry_rowid, rid_epoch in db.conn.execute(
        "SELECT entry_rowid, value_num FROM entry_fields "
        "WHERE key='recurrence_id_epoch'"
    ):
        key = (sources[entry_rowid], uids[entry_rowid])
        out.setdefault(key, set()).add(int(rid_epoch))
    return out


def _masters(db, start_epoch, end_epoch):
    """Fetch the recurring masters whose recurrence overlaps the window.

    Same shape as `_suppression_map`: single-pass index scans joined in
    Python instead of a nested-loop SQL join over ``entry_fields`` key
    ranges (measured 205ms → ~5ms on the 3,867-card deck). The
    ``recurrence_end_epoch`` bound (importer-computed) keeps long-dead
    recurrences from ever being loaded or expanded — on this deck it cuts
    the masters parsed per window from 442 to the few actually alive in it.
    A master without the bound (authored before the field existed) reads as
    unbounded: never hidden, merely unfiltered until its next re-render.
    """
    starts = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_num FROM entry_fields WHERE key='dtstart_epoch'"
        ).fetchall()
    )
    ends = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_num FROM entry_fields "
            "WHERE key='recurrence_end_epoch'"
        ).fetchall()
    )
    rowids = [
        rowid
        for (rowid,) in db.conn.execute(
            "SELECT entry_rowid FROM entry_fields WHERE key='rrule'"
        )
        if starts[rowid] < end_epoch
        and ends.get(rowid, RECURRENCE_FOREVER_EPOCH) > start_epoch
    ]
    if not rowids:
        return []
    marks = ",".join("?" * len(rowids))
    return db.conn.execute(
        f"SELECT yaml_text, body FROM entries WHERE rowid IN ({marks})", rowids
    ).fetchall()


def _expand_master(card, start, end, start_epoch, end_epoch, suppression, hide):
    if card.yaml["status"] == "CANCELLED":
        return []
    dtstart = card.yaml["dtstart"]
    duration = card.yaml["dtend"] - dtstart
    all_day = card.yaml["all_day"]
    uid = card.yaml["uid"]
    anchor = (
        _dt.datetime(dtstart.year, dtstart.month, dtstart.day, tzinfo=_dt.timezone.utc)
        if all_day
        else dtstart.astimezone(ZoneInfo(card.yaml["tzid"]))
    )
    rule = rrulestr(normalise_until(card.yaml["rrule"]), dtstart=anchor)
    suppress = {_instant(d) for d in card.yaml.get("exdate", [])}
    suppress |= suppression.get((card.yaml["source"], uid), set())
    out = []
    seen = set()
    generated = list(rule.between(start - duration, end, inc=False))
    rdates = [
        _dt.datetime(r.year, r.month, r.day, tzinfo=_dt.timezone.utc) if all_day else r
        for r in card.yaml.get("rdate", [])
    ]
    for occ in generated + rdates:
        occ_end = occ + duration
        if not (_instant(occ) < end_epoch and _instant(occ_end) > start_epoch):
            continue
        if _instant(occ) in suppress or _instant(occ) in seen:
            continue
        seen.add(_instant(occ))
        hidden = hide(card, _instant(occ))
        if all_day:
            out.append(Occurrence(card, occ.date(), occ_end.date(), True, hidden))
        else:
            out.append(Occurrence(card, occ, occ_end, True, hidden))
    return out


def events_in_window(db, start, end):
    """Return the event occurrences overlapping the half-open window ``[start, end)``.

    Combines non-recurring events (and RECURRENCE-ID exceptions, which are concrete
    cards) overlapping the window with recurring masters expanded across it —
    EXDATEs subtracted and overridden/cancelled slots suppressed. The result is
    unsorted; the caller buckets/sorts as the view requires.

    Args:
        db: An open ``mddb.MDDB`` for the deck (the caller owns the connection).
        start: Window start, a tz-aware ``datetime.datetime``.
        end: Window end (exclusive), a tz-aware ``datetime.datetime``.

    Returns:
        A list of `Occurrence`.

    Raises:
        ValueError: ``start`` or ``end`` is a naive ``datetime``.
    """
    start_epoch, end_epoch = _instant(start), _instant(end)
    hide = _hide_policy(db)
    occurrences = _concrete(db, start_epoch, end_epoch, hide)
    suppression = _suppression_map(db)
    masters = _masters(db, start_epoch, end_epoch)
    for yaml_text, body in masters:
        occurrences.extend(
            _expand_master(
                _card(yaml_text, body),
                start,
                end,
                start_epoch,
                end_epoch,
                suppression,
                hide,
            )
        )
    return occurrences
