"""Resolve an mddb calendar deck into the event occurrences within a time window.

Recurring masters carry an ``rrule``+``exdate`` and are expanded at read time
(plain instances are never materialised); RECURRENCE-ID exceptions are their own
cards keyed ``uid``+``recurrence_id``. `events_in_window` returns the occurrences
overlapping a half-open window — expanding masters, subtracting EXDATEs, and
suppressing slots overridden by exception cards (which surface concretely at their
own time). Library code composing over the public `mddb.MDDB` surface; the
substrate stays calendar-agnostic.
"""

import datetime as _dt
import re as _re
from dataclasses import dataclass

import yaml as _yaml
from dateutil.rrule import rrulestr
from mddb import Card

_LOADER = getattr(_yaml, "CSafeLoader", _yaml.SafeLoader)
"""SafeLoader semantics on the resolver's hottest path.

``CSafeLoader`` is the libyaml C implementation of ``SafeLoader`` — identical
parse semantics, ~9x faster (measured 199ms → 23ms for a month window's 450
cards on the Research deck). Falls back to the pure-Python ``SafeLoader`` on
PyYAML builds without libyaml.
"""


def _card(yaml_text, body):
    return Card(yaml=_yaml.load(yaml_text, Loader=_LOADER), body=body)


def _normalise_until(rrule):
    """Coerce a DATE-form ``RRULE`` ``UNTIL`` to end-of-day UTC.

    `dateutil` requires the ``UNTIL`` value be a UTC ``datetime`` when DTSTART is
    tz-aware, but real Google exports sometimes emit a DATE-form ``UNTIL=20200412``
    (observed in 2/442 Research masters). Map a date-form ``UNTIL`` to that day's
    end in UTC; any other form (notably a well-formed ``...Z`` datetime) is left
    untouched and `dateutil` raises naturally if it is malformed.

    Args:
        rrule: The stored RRULE string (no ``RRULE:`` prefix).

    Returns:
        The RRULE string with a date-form ``UNTIL`` normalised to UTC.
    """
    return _re.sub(r"UNTIL=([0-9]{8})(?=;|$)", r"UNTIL=\1T235959Z", rrule)


@dataclass
class Occurrence:
    """One concrete event occurrence to render.

    Attributes:
        card: The mddb ``Card`` — the recurring master for a generated instance,
            or the concrete (single / exception) card itself.
        start: This occurrence's start — a ``datetime.date`` for an all-day event,
            a tz-aware ``datetime.datetime`` otherwise.
        end: This occurrence's end, with the same typing as ``start``.
        recurring: ``True`` if generated by expanding a master's ``rrule``;
            ``False`` for a stored concrete card.
    """

    card: Card
    start: _dt.date | _dt.datetime
    end: _dt.date | _dt.datetime
    recurring: bool


def _instant(value):
    """Return the UTC-second epoch for a ``date`` or tz-aware ``datetime``.

    Mirrors the importer's epoch convention so ``date`` and ``datetime`` values
    compare uniformly: a ``date`` maps to its UTC-midnight epoch; a ``datetime``
    must be tz-aware.

    Args:
        value: A ``datetime.date`` or tz-aware ``datetime.datetime``.

    Returns:
        Integer UTC-second epoch.

    Raises:
        ValueError: ``value`` is a naive ``datetime`` (no silent localisation).
    """
    if isinstance(value, _dt.datetime):
        if value.tzinfo is None:
            raise ValueError(f"naive datetime not supported: {value!r}")
        return int(value.timestamp())
    midnight = _dt.datetime(value.year, value.month, value.day, tzinfo=_dt.timezone.utc)
    return int(midnight.timestamp())


def _concrete(db, start_epoch, end_epoch):
    rows = db.conn.execute(
        "SELECT e.yaml_text, e.body FROM entries e "
        "JOIN entry_fields ds ON ds.entry_rowid=e.rowid AND ds.key='dtstart_epoch' "
        "JOIN entry_fields de ON de.entry_rowid=e.rowid AND de.key='dtend_epoch' "
        "LEFT JOIN entry_fields rr ON rr.entry_rowid=e.rowid AND rr.key='rrule' "
        "WHERE ds.value_num < ? AND de.value_num > ? AND rr.entry_rowid IS NULL",
        (end_epoch, start_epoch),
    ).fetchall()
    out = []
    for yaml_text, body in rows:
        card = _card(yaml_text, body)
        if card.yaml["status"] == "CANCELLED":
            continue
        out.append(Occurrence(card, card.yaml["dtstart"], card.yaml["dtend"], False))
    return out


def _suppression_map(db):
    """Map each uid to the recurrence-id epochs its exception cards override.

    Two single-pass index scans joined in Python: SQLite has no
    ``(entry_rowid, key)`` index on ``entry_fields``, so joining the two key
    ranges in SQL nested-loops every uid row against every exception row
    (measured 436ms on the 3,867-card deck vs ~5ms this way).
    """
    uids = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_str FROM entry_fields WHERE key='uid'"
        ).fetchall()
    )
    out = {}
    for entry_rowid, rid_epoch in db.conn.execute(
        "SELECT entry_rowid, value_num FROM entry_fields "
        "WHERE key='recurrence_id_epoch'"
    ):
        out.setdefault(uids[entry_rowid], set()).add(int(rid_epoch))
    return out


def _masters(db, end_epoch):
    """Fetch every recurring master rooted before ``end_epoch``.

    Same shape as `_suppression_map`: two single-pass index scans joined in
    Python instead of a nested-loop SQL join over two ``entry_fields`` key
    ranges (measured 205ms → ~5ms on the 3,867-card deck).
    """
    starts = dict(
        db.conn.execute(
            "SELECT entry_rowid, value_num FROM entry_fields WHERE key='dtstart_epoch'"
        ).fetchall()
    )
    rowids = [
        rowid
        for (rowid,) in db.conn.execute(
            "SELECT entry_rowid FROM entry_fields WHERE key='rrule'"
        )
        if starts[rowid] < end_epoch
    ]
    marks = ",".join("?" * len(rowids))
    return db.conn.execute(
        f"SELECT yaml_text, body FROM entries WHERE rowid IN ({marks})", rowids
    ).fetchall()


def _expand_master(card, start, end, start_epoch, end_epoch, suppression):
    if card.yaml["status"] == "CANCELLED":
        return []
    dtstart = card.yaml["dtstart"]
    duration = card.yaml["dtend"] - dtstart
    all_day = card.yaml["all_day"]
    anchor = (
        _dt.datetime(dtstart.year, dtstart.month, dtstart.day, tzinfo=_dt.timezone.utc)
        if all_day
        else dtstart
    )
    rule = rrulestr(_normalise_until(card.yaml["rrule"]), dtstart=anchor)
    suppress = {_instant(d) for d in card.yaml.get("exdate", [])}
    suppress |= suppression.get(card.yaml["uid"], set())
    out = []
    for occ in rule.between(start - duration, end, inc=False):
        occ_end = occ + duration
        if not (_instant(occ) < end_epoch and _instant(occ_end) > start_epoch):
            continue
        if _instant(occ) in suppress:
            continue
        if all_day:
            out.append(Occurrence(card, occ.date(), occ_end.date(), True))
        else:
            out.append(Occurrence(card, occ, occ_end, True))
    return out


def events_in_window(db, start, end):
    """Return the event occurrences overlapping the half-open window ``[start, end)``.

    Combines non-recurring events (and RECURRENCE-ID exceptions, which are concrete
    cards) overlapping the window with recurring masters expanded across it —
    EXDATEs subtracted and overridden/cancelled slots suppressed. The result is
    unsorted; the caller buckets/sorts as the view requires.

    Args:
        db: An open ``mddb.MDDB`` for the deck (the caller owns the connection).
        start: Window start, a tz-aware ``datetime.datetime``.
        end: Window end (exclusive), a tz-aware ``datetime.datetime``.

    Returns:
        A list of `Occurrence`.

    Raises:
        ValueError: ``start`` or ``end`` is a naive ``datetime``.
    """
    start_epoch, end_epoch = _instant(start), _instant(end)
    occurrences = _concrete(db, start_epoch, end_epoch)
    suppression = _suppression_map(db)
    masters = _masters(db, end_epoch)
    for yaml_text, body in masters:
        occurrences.extend(
            _expand_master(
                _card(yaml_text, body), start, end, start_epoch, end_epoch, suppression
            )
        )
    return occurrences
